
import type { Product, Review } from './types';

export const CATEGORIES: string[] = [
  "All",
  "Electronics",
  "Fashion",
  "Home & Kitchen",
  "Books",
  "Sports",
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Modern Wireless Headphones",
    price: 129.99,
    description: "Experience crystal clear audio with these noise-cancelling wireless headphones. Long-lasting battery and comfortable fit for all-day use.",
    category: "Electronics",
    imageUrl: "https://picsum.photos/seed/product1/600/600",
    rating: 4.5,
    reviewCount: 120,
  },
  {
    id: 2,
    name: "Classic Leather Wallet",
    price: 49.50,
    description: "A stylish and durable leather wallet with multiple card slots and a spacious bill compartment. Perfect for everyday use.",
    category: "Fashion",
    imageUrl: "https://picsum.photos/seed/product2/600/600",
    rating: 4.8,
    reviewCount: 250,
  },
  {
    id: 3,
    name: "Smart Coffee Maker",
    price: 89.99,
    description: "Brew the perfect cup of coffee from your phone. This smart coffee maker lets you schedule brewing times and customize strength.",
    category: "Home & Kitchen",
    imageUrl: "https://picsum.photos/seed/product3/600/600",
    rating: 4.2,
    reviewCount: 88,
  },
  {
    id: 4,
    name: "The Midnight Library",
    price: 15.99,
    description: "A bestselling novel by Matt Haig. A captivating story about choices, regrets, and the infinite possibilities of life.",
    category: "Books",
    imageUrl: "https://picsum.photos/seed/product4/600/600",
    rating: 4.9,
    reviewCount: 5400,
  },
  {
    id: 5,
    name: "Professional Yoga Mat",
    price: 35.00,
    description: "High-density, non-slip yoga mat for a comfortable and stable practice. Eco-friendly and easy to clean.",
    category: "Sports",
    imageUrl: "https://picsum.photos/seed/product5/600/600",
    rating: 4.7,
    reviewCount: 310,
  },
  {
    id: 6,
    name: "4K Streaming Dongle",
    price: 49.99,
    description: "Upgrade your TV to a smart TV with this 4K streaming device. Access all your favorite apps like Netflix, YouTube, and more.",
    category: "Electronics",
    imageUrl: "https://picsum.photos/seed/product6/600/600",
    rating: 4.6,
    reviewCount: 1500,
  },
  {
    id: 7,
    name: "Men's Casual Sneakers",
    price: 75.00,
    description: "Comfortable and stylish sneakers for daily wear. Made with breathable materials and a cushioned sole.",
    category: "Fashion",
    imageUrl: "https://picsum.photos/seed/product7/600/600",
    rating: 4.4,
    reviewCount: 450,
  },
  {
    id: 8,
    name: "Air Fryer XL",
    price: 119.00,
    description: "Enjoy your favorite fried foods with less oil. This extra-large air fryer is perfect for families.",
    category: "Home & Kitchen",
    imageUrl: "https://picsum.photos/seed/product8/600/600",
    rating: 4.8,
    reviewCount: 980,
  },
   {
    id: 9,
    name: "Gaming Mouse RGB",
    price: 59.99,
    description: "High-precision gaming mouse with customizable RGB lighting and programmable buttons. Ergonomic design for long gaming sessions.",
    category: "Electronics",
    imageUrl: "https://picsum.photos/seed/product9/600/600",
    rating: 4.7,
    reviewCount: 650,
  },
  {
    id: 10,
    name: "Denim Jacket",
    price: 85.00,
    description: "A timeless denim jacket that completes any casual outfit. Made from high-quality, durable denim.",
    category: "Fashion",
    imageUrl: "https://picsum.photos/seed/product10/600/600",
    rating: 4.6,
    reviewCount: 320,
  },
  {
    id: 11,
    name: "Stainless Steel Cookware Set",
    price: 199.99,
    description: "10-piece stainless steel cookware set. Includes pots, pans, and lids for all your cooking needs. Even heat distribution.",
    category: "Home & Kitchen",
    imageUrl: "https://picsum.photos/seed/product11/600/600",
    rating: 4.5,
    reviewCount: 180,
  },
  {
    id: 12,
    name: "Adjustable Dumbbells Set",
    price: 249.00,
    description: "Save space with this adjustable dumbbell set. Easily change weights from 5 to 52.5 lbs. Perfect for a home gym.",
    category: "Sports",
    imageUrl: "https://picsum.photos/seed/product12/600/600",
    rating: 4.9,
    reviewCount: 720,
  },
];

export const REVIEWS: Review[] = [
    {
        id: 1,
        productId: 1,
        author: "John D.",
        rating: 5,
        comment: "Absolutely amazing sound quality and the noise cancellation is top-notch. Worth every penny!",
        date: "May 20, 2024",
    },
    {
        id: 2,
        productId: 1,
        author: "Jane S.",
        rating: 4,
        comment: "Very comfortable for long listening sessions. The battery life is impressive. Sometimes disconnects briefly, but it's rare.",
        date: "May 15, 2024",
    },
    {
        id: 3,
        productId: 8,
        author: "Mike T.",
        rating: 5,
        comment: "This air fryer changed my life! It's so easy to use and everything comes out crispy and delicious. The XL size is perfect for my family of four.",
        date: "April 30, 2024",
    },
    {
        id: 4,
        productId: 4,
        author: "Emily R.",
        rating: 5,
        comment: "One of the best books I've read this year. The story is beautiful and thought-provoking. I couldn't put it down.",
        date: "June 1, 2024",
    },
    {
        id: 5,
        productId: 4,
        author: "Chris B.",
        rating: 4,
        comment: "A really interesting concept and well-written. The ending felt a little rushed to me, but I still highly recommend it.",
        date: "May 28, 2024",
    }
];
